# -*- coding: utf-8 -*-
"""ProyectoStreamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17t4tKNaK4gSdUtTv2fNyu_ZyF14EcB5E
"""

import numpy as np
import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

st.write('Predicción de gastos')
st.image("gastos.jpg", caption="Cuidando tus finanzas")
st.header('Datos:')

def user_input_features():

    Presupuesto = st.number_input('Presupuesto:', min_value=0.0, value=0.0)

    Tiempo = st.number_input('Tiempo:', min_value=0.0, value=0.0)

    Tipo = st.number_input('Tipo de actividad: (1:Alimento, 2:Salud, 3:Deporte, 4:Ocio, 5:Entretenimiento, 6:Académico, 7:Transporte)',
                           min_value=1, max_value=7)

    Momento = st.number_input('Momento (1=Mañana, 2=Tarde, 3=Noche):',
                              min_value=1, max_value=3)

    Personas = st.number_input('Número de personas:', min_value=1, value=1, step=1)

    user_input_data = {
        'Presupuesto': Presupuesto,
        'Tiempo': Tiempo,
        'Tipo': Tipo,
        'Momento': Momento,
        'Personas': Personas
    }

    features = pd.DataFrame(user_input_data, index=[0])
    return features

df = user_input_features()

datos = pd.read_csv('2Registro1613874.csv')

Y = datos['Costo']
X = datos[['Presupuesto', 'Tiempo invertido', 'Tipo', 'Momento', 'No. de personas']]
modelo = LinearRegression()
modelo.fit(X, Y)

prediccion = modelo.predict(df)[0]

st.write(f'Predicción de costo: ${prediccion:.2f}')